# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MartG_TestStatC <- function(n, k, X, Xj) {
    .Call('_HDTSA_MartG_TestStatC', PACKAGE = 'HDTSA', n, k, X, Xj)
}

MartG_ftC <- function(n, k, p, d, X, Xj) {
    .Call('_HDTSA_MartG_ftC', PACKAGE = 'HDTSA', n, k, p, d, X, Xj)
}

MartG_bootc <- function(n, k, p, d, B, bn, method, ft, Xi_temp) {
    .Call('_HDTSA_MartG_bootc', PACKAGE = 'HDTSA', n, k, p, d, B, bn, method, ft, Xi_temp)
}

sigmak <- function(Y, Y_mean, k, n) {
    .Call('_HDTSA_sigmak', PACKAGE = 'HDTSA', Y, Y_mean, k, n)
}

thresh_C <- function(mat, delta) {
    .Call('_HDTSA_thresh_C', PACKAGE = 'HDTSA', mat, delta)
}

MatMult <- function(A, B) {
    .Call('_HDTSA_MatMult', PACKAGE = 'HDTSA', A, B)
}

WN_teststatC <- function(X, n, p, k) {
    .Call('_HDTSA_WN_teststatC', PACKAGE = 'HDTSA', X, n, p, k)
}

WN_ftC <- function(n, k, p, X, X_mean) {
    .Call('_HDTSA_WN_ftC', PACKAGE = 'HDTSA', n, k, p, X, X_mean)
}

WN_bootc <- function(n, k, p, B, bn, method, ft, X, sigma_zero, Xi_temp) {
    .Call('_HDTSA_WN_bootc', PACKAGE = 'HDTSA', n, k, p, B, bn, method, ft, X, sigma_zero, Xi_temp)
}

bandwith <- function(ft, k, p, d, ken_type) {
    .Call('_HDTSA_bandwith', PACKAGE = 'HDTSA', ft, k, p, d, ken_type)
}

TaperQsC <- function(x) {
    .Call('_HDTSA_TaperQsC', PACKAGE = 'HDTSA', x)
}

TaperBartC <- function(x) {
    .Call('_HDTSA_TaperBartC', PACKAGE = 'HDTSA', x)
}

TaperFlatC <- function(x, c) {
    .Call('_HDTSA_TaperFlatC', PACKAGE = 'HDTSA', x, c)
}

CmpGammaC <- function(Vt) {
    .Call('_HDTSA_CmpGammaC', PACKAGE = 'HDTSA', Vt)
}

EvalGammaJC <- function(Gamma, j, len) {
    .Call('_HDTSA_EvalGammaJC', PACKAGE = 'HDTSA', Gamma, j, len)
}

CmpRhoC <- function(Gamma, len) {
    .Call('_HDTSA_CmpRhoC', PACKAGE = 'HDTSA', Gamma, len)
}

EvalRhoMC <- function(Rho, m, len) {
    .Call('_HDTSA_EvalRhoMC', PACKAGE = 'HDTSA', Rho, m, len)
}

CmpHatSC <- function(Rho, C0, KT, cef, p, len) {
    .Call('_HDTSA_CmpHatSC', PACKAGE = 'HDTSA', Rho, C0, KT, cef, p, len)
}

SpecEstC <- function(Gamma, n, p, r, K, cross_indices, J_set, l_band, flag_c) {
    .Call('_HDTSA_SpecEstC', PACKAGE = 'HDTSA', Gamma, n, p, r, K, cross_indices, J_set, l_band, flag_c)
}

TestStatC <- function(Gamma, n, p, r, K, cross_indices, J_set, l_band, flag_c) {
    .Call('_HDTSA_TestStatC', PACKAGE = 'HDTSA', Gamma, n, p, r, K, cross_indices, J_set, l_band, flag_c)
}

CEst2C <- function(x, Gamma, n_tilde, n, p, r, cross_indices, l_band) {
    .Call('_HDTSA_CEst2C', PACKAGE = 'HDTSA', x, Gamma, n_tilde, n, p, r, cross_indices, l_band)
}

CEst3C <- function(x, Gamma, n_tilde, n, p, r, cross_indices, l_band) {
    .Call('_HDTSA_CEst3C', PACKAGE = 'HDTSA', x, Gamma, n_tilde, n, p, r, cross_indices, l_band)
}

BandEstC <- function(Chat, n_tilde, r, l_band, type) {
    .Call('_HDTSA_BandEstC', PACKAGE = 'HDTSA', Chat, n_tilde, r, l_band, type)
}

etaC <- function(n, p, B, n_tilde, bn, type) {
    .Call('_HDTSA_etaC', PACKAGE = 'HDTSA', n, p, B, n_tilde, bn, type)
}

LongCovEstC <- function(n_tilde, ln, r, Shat_c, Chat, Kern) {
    .Call('_HDTSA_LongCovEstC', PACKAGE = 'HDTSA', n_tilde, ln, r, Shat_c, Chat, Kern)
}

TestStarC <- function(x, GhatC, n_tilde, n, p, r, K, flag_c, cross_indices, J_set, l_band, B_monte, type) {
    .Call('_HDTSA_TestStarC', PACKAGE = 'HDTSA', x, GhatC, n_tilde, n, p, r, K, flag_c, cross_indices, J_set, l_band, B_monte, type)
}

minor_P <- function(Wr, Ws, d1, d2) {
    .Call('_HDTSA_minor_P', PACKAGE = 'HDTSA', Wr, Ws, d1, d2)
}

Vech2Mat_new <- function(P, d) {
    .Call('_HDTSA_Vech2Mat_new', PACKAGE = 'HDTSA', P, d)
}

