# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MartG_TestStatC <- function(n, k, X, Xj) {
    .Call('_HDTSA_MartG_TestStatC', PACKAGE = 'HDTSA', n, k, X, Xj)
}

MartG_ftC <- function(n, k, p, d, X, Xj) {
    .Call('_HDTSA_MartG_ftC', PACKAGE = 'HDTSA', n, k, p, d, X, Xj)
}

MartG_XiC <- function(n, k, p, B, bn, ken_sign) {
    .Call('_HDTSA_MartG_XiC', PACKAGE = 'HDTSA', n, k, p, B, bn, ken_sign)
}

MartG_bandwith <- function(ft, k, p, d, ken_type) {
    .Call('_HDTSA_MartG_bandwith', PACKAGE = 'HDTSA', ft, k, p, d, ken_type)
}

MartG_bootc <- function(n, k, p, d, B, bn, method, ft) {
    .Call('_HDTSA_MartG_bootc', PACKAGE = 'HDTSA', n, k, p, d, B, bn, method, ft)
}

sigmak <- function(Y, Y_mean, k, n) {
    .Call('_HDTSA_sigmak', PACKAGE = 'HDTSA', Y, Y_mean, k, n)
}

thresh_C <- function(sigmaY, Y, Y_mean, k, n, p, deltafinal) {
    .Call('_HDTSA_thresh_C', PACKAGE = 'HDTSA', sigmaY, Y, Y_mean, k, n, p, deltafinal)
}

MatMult <- function(A, B) {
    .Call('_HDTSA_MatMult', PACKAGE = 'HDTSA', A, B)
}

WN_teststatC <- function(X, n, p, k) {
    .Call('_HDTSA_WN_teststatC', PACKAGE = 'HDTSA', X, n, p, k)
}

WN_ftC <- function(n, k, p, X, X_mean) {
    .Call('_HDTSA_WN_ftC', PACKAGE = 'HDTSA', n, k, p, X, X_mean)
}

WN_XiC <- function(n, k, p, B, bn, ken_sign) {
    .Call('_HDTSA_WN_XiC', PACKAGE = 'HDTSA', n, k, p, B, bn, ken_sign)
}

WN_bandwith <- function(ft, k, p, ken_type) {
    .Call('_HDTSA_WN_bandwith', PACKAGE = 'HDTSA', ft, k, p, ken_type)
}

WN_bootc <- function(n, k, p, B, bn, method, ft, X, sigma_zero) {
    .Call('_HDTSA_WN_bootc', PACKAGE = 'HDTSA', n, k, p, B, bn, method, ft, X, sigma_zero)
}

